apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-runtime-config
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  runtime-config.js: |
    // runtime-config injected by Kubernetes ConfigMap
    window.__RUNTIME_CONFIG__ = window.__RUNTIME_CONFIG__ || {};
    window.__RUNTIME_CONFIG__.MIP_BACKEND_URL = "{{ .Values.env.MIP_BACKEND_URL }}";
